# homework java gradle
#
#
name: jav gradle ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: java_gradle
        uses: actions/checkout@v3

      - name: Setup jdk 11
        uses: actions/setup-java@v3
        with: 
          java-version: '11'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
          


